name: frankjaeger
favicon: null
layout_spectrum: 0.6130559898447245
typography_spectrum: 0.8011806695722044
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8582183818798512
  lightness: 0.7359949473757297
  saturation: 0.8319552424363792
  rhythmicContrast: 0.001359737478196621
purpose: []
