name: frankjaeger
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73977
title: Frank Jaeger RTD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0076ec'
    - '#760000'
    - '#ffffff'
    - '#2f2f2f'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
